# Generated by Django 3.0.4 on 2020-04-06 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '地址'},
        ),
        migrations.AlterModelOptions(
            name='constructionunit',
            options={'verbose_name': '建设单位'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '联系人'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门'},
        ),
        migrations.AlterModelOptions(
            name='designinstitute',
            options={'verbose_name': '设计院'},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': '专家'},
        ),
        migrations.AlterModelOptions(
            name='expertreview',
            options={'verbose_name': '专家评审会'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-apply_date'], 'verbose_name': '项目'},
        ),
        migrations.AlterModelOptions(
            name='reviewcom',
            options={'verbose_name': '专家组成员'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '部门参会人员'},
        ),
        migrations.AddField(
            model_name='project',
            name='apply_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 14, 25, 46, 228555, tzinfo=utc)),
        ),
    ]
