# Generated by Django 3.0.4 on 2020-04-06 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20200406_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-com_date'], 'verbose_name': '规委会'},
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='com_data',
            new_name='com_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='apply_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
